{
    "type": "bundle",
    "id": "bundle--0e1264dc-2f48-4cb8-bf9e-d38cfc2232ad",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--3b901e6b-566e-4a20-b524-029de6047543",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2025-01-29T00:20:42.424857Z",
            "modified": "2025-01-29T00:20:42.424857Z",
            "name": "CVE-2025-24478",
            "description": "A denial-of-service vulnerability exists in the affected products. The vulnerability could allow a remote, non-privileged user to send malicious requests resulting in a major nonrecoverable fault causing a denial-of-service.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2025-24478"
                }
            ]
        }
    ]
}