{
    "type": "bundle",
    "id": "bundle--457d8943-faa0-4238-a224-d8931f2e36cf",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--245ad8a0-bf9e-44fa-b23a-cea5a0ca1953",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2024-10-02T00:20:34.508778Z",
            "modified": "2024-10-02T00:20:34.508778Z",
            "name": "CVE-2024-8421",
            "description": "This CVE has been rejected.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2024-8421"
                }
            ]
        }
    ]
}