{
    "type": "bundle",
    "id": "bundle--e543f084-8f10-48f3-a0e0-273acf0032c5",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--0c7e0908-ef46-4945-a218-30bea6fa82fd",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2025-05-02T00:23:42.532443Z",
            "modified": "2025-05-02T00:23:42.532443Z",
            "name": "CVE-2025-23162",
            "description": "In the Linux kernel, the following vulnerability has been resolved:\n\ndrm/xe/vf: Don't try to trigger a full GT reset if VF\n\nVFs don't have access to the GDRST(0x941c) register that driver\nuses to reset a GT. Attempt to trigger a reset using debugfs:\n\n $ cat /sys/kernel/debug/dri/0000:00:02.1/gt0/force_reset\n\nor due to a hang condition detected by the driver leads to:\n\n [ ] xe 0000:00:02.1: [drm] GT0: trying reset from force_reset [xe]\n [ ] xe 0000:00:02.1: [drm] GT0: reset queued\n [ ] xe 0000:00:02.1: [drm] GT0: reset started\n [ ] ------------[ cut here ]------------\n [ ] xe 0000:00:02.1: [drm] GT0: VF is trying to write 0x1 to an inaccessible register 0x941c+0x0\n [ ] WARNING: CPU: 3 PID: 3069 at drivers/gpu/drm/xe/xe_gt_sriov_vf.c:996 xe_gt_sriov_vf_write32+0xc6/0x580 [xe]\n [ ] RIP: 0010:xe_gt_sriov_vf_write32+0xc6/0x580 [xe]\n [ ] Call Trace:\n [ ]  <TASK>\n [ ]  ? show_regs+0x6c/0x80\n [ ]  ? __warn+0x93/0x1c0\n [ ]  ? xe_gt_sriov_vf_write32+0xc6/0x580 [xe]\n [ ]  ? report_bug+0x182/0x1b0\n [ ]  ? handle_bug+0x6e/0xb0\n [ ]  ? exc_invalid_op+0x18/0x80\n [ ]  ? asm_exc_invalid_op+0x1b/0x20\n [ ]  ? xe_gt_sriov_vf_write32+0xc6/0x580 [xe]\n [ ]  ? xe_gt_sriov_vf_write32+0xc6/0x580 [xe]\n [ ]  ? xe_gt_tlb_invalidation_reset+0xef/0x110 [xe]\n [ ]  ? __mutex_unlock_slowpath+0x41/0x2e0\n [ ]  xe_mmio_write32+0x64/0x150 [xe]\n [ ]  do_gt_reset+0x2f/0xa0 [xe]\n [ ]  gt_reset_worker+0x14e/0x1e0 [xe]\n [ ]  process_one_work+0x21c/0x740\n [ ]  worker_thread+0x1db/0x3c0\n\nFix that by sending H2G VF_RESET(0x5507) action instead.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2025-23162"
                }
            ]
        }
    ]
}