{
    "type": "bundle",
    "id": "bundle--59e907cd-94ee-4fd4-986e-74b920421546",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--2ce59ba8-61e0-4690-95bd-d07f41815976",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2025-04-04T00:22:30.966715Z",
            "modified": "2025-04-04T00:22:30.966715Z",
            "name": "CVE-2025-32049",
            "description": "A flaw was found in libsoup. The SoupWebsocketConnection may accept a large WebSocket message, which may cause libsoup to allocate memory and lead to a denial of service (DoS).",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2025-32049"
                }
            ]
        }
    ]
}