{
    "type": "bundle",
    "id": "bundle--32a3194c-9caf-44e0-9213-0f0f6fcaf89f",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--c6319523-0a7d-4629-b552-ec90bec20ecd",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2024-07-30T00:18:44.863607Z",
            "modified": "2024-07-30T00:18:44.863607Z",
            "name": "CVE-2024-41034",
            "description": "In the Linux kernel, the following vulnerability has been resolved:\n\nnilfs2: fix kernel bug on rename operation of broken directory\n\nSyzbot reported that in rename directory operation on broken directory on\nnilfs2, __block_write_begin_int() called to prepare block write may fail\nBUG_ON check for access exceeding the folio/page size.\n\nThis is because nilfs_dotdot(), which gets parent directory reference\nentry (\"..\") of the directory to be moved or renamed, does not check\nconsistency enough, and may return location exceeding folio/page size for\nbroken directories.\n\nFix this issue by checking required directory entries (\".\" and \"..\") in\nthe first chunk of the directory in nilfs_dotdot().",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2024-41034"
                }
            ]
        }
    ]
}