{
    "type": "bundle",
    "id": "bundle--82fb0778-df89-4aca-b9d6-104d44a98b8e",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--7087bb6e-693b-40f2-8900-0c602b13605f",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2025-02-14T00:20:57.645562Z",
            "modified": "2025-02-14T00:20:57.645562Z",
            "name": "CVE-2024-57782",
            "description": "An issue in Docker-proxy v18.09.0 allows attackers to cause a denial of service.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2024-57782"
                }
            ]
        }
    ]
}